apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: ekart  
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart  
    spec:
      containers:
        - name: ekart-container
          image: ekart:latest
          ports:
            - containerPort: 8080